### ISSUE TITLE
feat : 강사(instructor)

### ISSUE THREAD

**Issue by jeongaaa** [f-lab-edu/fitness-partner#1]
## 설명(Description)
- 유저로 회원가입 한 회원이면 누구나 강사로 전환 가능
- 유저는 강사로 전환 후 레슨 등록 가능
- 강사 전환 후 자격증 등록 가능

## To Do List
- [x] 유저에서 강사 전환(강사 등록)
- [x] 강사 활동지역 주소 정보 업데이트
- [x] 강사 정보 조회

❌ 강사 비활성화

## 추가내용
-  강사로 전환 시 가장 중요한 것은 강사의 활동 지역이라고 생각했다.
    강사의 활동 반경을 기반으로 유저들과 추천 매칭을 할 수 있다.
    => 강사의 주소 관련 데이터를 더 세밀하게 DB에 저장 할 수 있도록 수정 필요

**Comment by yarogono** [comment]
Spring Security 적용 후 To Do List

- 강사 정보 수정 자격 검증

   - 유저 권한(Role) 이슈에서 처리 예정

**Comment by yarogono** [comment]
### 강사 비활성화 기능 제거

- 강사도 유저이기 때문에 유저 비활성화와 기능이 겹침
- ❌유저 탈퇴(비활성화) 시 강사도 같이 비활성화 되도록 변경
- 유저 Service layer에서 강사도 같이 비활성화 시 결합도가 너무 높아질 것 같음

     - 강사 Service layer에 비활성화 메서드 구현 후 유저 서비스 레이어에서 호출하는 방식으로 고민
     - 유저 탈퇴 시 강사가 등록한 레슨도 전부 비활성화 해야함
